services:
  metabase-app:
    image: metabase/metabase-enterprise:v1.49.8
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5m
    # environment:
    #   - JAVA_OPTS=-Dlog4j.configurationFile=file:///tmp/log4j2.xml
    # volumes:
    #   - ./config/log4j2.xml:/tmp/log4j2.xml
    container_name: metabase-app
    # Removed ports to not expose private service
    # ports:
    #   - "3000:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_SITE_URL=https://PUBLIC_DOMAIN:443
    networks:
      - metabase-internal
  nginx:
    image: nginx:1.25.5
    container_name: nginx
    restart: unless-stopped
    ports:
      - 443:443
    volumes:
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/certs/:/ssl/
    depends_on:
      - metabase-app
    networks:
      - metabase-internal
networks:
  metabase-internal:
    driver: bridge
